### PR TITLE
new: added AllIdentities() as part of the ModelManager interface

### PR DESCRIPTION
**Pull request by primalmotion**

### CODE REVIEW

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reportsquery",
    "component": "backend",
    "pr-id": "970",
    "commit-sha": "3dda44bcf528f1c6e512731a3f8fdb80b3659e92",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "gaia",
    "pr-id": "598",
    "commit-sha": "ca2b6ea4f7b80778d7c676734cffec0e1a7912bb",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "manipulate",
    "pr-id": "132",
    "commit-sha": "cd466f9d0ee90f02631da6c2175c20f20833f859",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "elemental",
    "pr-id": "84",
    "commit-sha": "c83e49cd5bb0d53140d4c5612e5a21d5f564ae28",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reportsquery",
    "component": "elemental",
    "pr-id": "84",
    "commit-sha": "c83e49cd5bb0d53140d4c5612e5a21d5f564ae28",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "backend",
    "pr-id": "970",
    "commit-sha": "d4bd8617cbfaea9539d8b9981ed12ec7067eca59",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "gaia",
    "pr-id": "598",
    "commit-sha": "8fc366d2debd9587de336300d74cbb2445b4f0dd",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "manipulate",
    "pr-id": "132",
    "commit-sha": "1ee30dd5bba93ff56751722aaa2dea49d6180b8d",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reportsquery",
    "component": "gaia",
    "pr-id": "598",
    "commit-sha": "8fc366d2debd9587de336300d74cbb2445b4f0dd",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "manipulate",
    "pr-id": "132",
    "commit-sha": "1ee30dd5bba93ff56751722aaa2dea49d6180b8d",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "elemental",
    "pr-id": "84",
    "commit-sha": "c83e49cd5bb0d53140d4c5612e5a21d5f564ae28",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "backend",
    "pr-id": "970",
    "commit-sha": "7f16b8e020ee6a0aa3113e8ae6e14650d027060d",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reportsquery",
    "component": "gaia",
    "pr-id": "598",
    "commit-sha": "8fc366d2debd9587de336300d74cbb2445b4f0dd",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "manipulate",
    "pr-id": "132",
    "commit-sha": "1ee30dd5bba93ff56751722aaa2dea49d6180b8d",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "elemental",
    "pr-id": "84",
    "commit-sha": "c83e49cd5bb0d53140d4c5612e5a21d5f564ae28",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "backend",
    "pr-id": "970",
    "commit-sha": "7f16b8e020ee6a0aa3113e8ae6e14650d027060d",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reportsquery",
    "component": "elemental",
    "pr-id": "84",
    "commit-sha": "c83e49cd5bb0d53140d4c5612e5a21d5f564ae28",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "backend",
    "pr-id": "970",
    "commit-sha": "26bc11414f2b20b084f06d3598acce3e06701c38",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "gaia",
    "pr-id": "598",
    "commit-sha": "8fc366d2debd9587de336300d74cbb2445b4f0dd",
    "pipeline": "master"
  },
  {
    "project": "reportsquery",
    "component": "manipulate",
    "pr-id": "132",
    "commit-sha": "040fe37f1e7dd0cf7bb2f98ec321d9b2b9df249c",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
