### PR TITLE
new: support extension bson_name

### PR DESCRIPTION
**Pull request by primalmotion**
This attribute extension allows to use a custom name for the
attribute during bson Marshaling/Unmarshaling

### CODE REVIEW

**Comment by aaslamin** [comment]
FYI @primalmotion 

https://travis-ci.org/github/aporeto-inc/elemental/builds/703717307
```
[/home/travis/gopath/src/github.com/aporeto-inc/elemental/cmd/elegen/static/bindata.go:30] - G110 (CWE-409): Potential DoS vulnerability via decompression bomb (Confidence: MEDIUM, Severity: MEDIUM)
  > io.Copy(&buf, gz)
```

**Comment by primalmotion** [comment]
It seems you are not using the latest version of aporeto's fork for go bindata.

**Comment by aaslamin** [comment]
> It seems you are not using the latest version of aporeto's fork for go bindata.

@primalmotion good 👀

I re-generated just now via the latest forked go-bindata master and it added the `nosec` annotation on the offending line.

**Comment by aaslamin** [comment]
Will re-open as another PR so @primalmotion doesn't need to approve his own 😉

**Pull request closed without merging**
