### PR TITLE
encode: fix nil check

### PR DESCRIPTION
**Pull request by aaslamin**
https://github.com/aporeto-inc/elemental/blob/master/encoding.go#L144

An interface will only be `nil`, *if and only if*, both it's type and value are nil. If the caller of `Encode` passes in a `nil` pointer here, this condition would not trigger because the interface is not actually nil anymore as it now has a type set (i.e. `*T`) even though it's value is `nil`!

https://play.golang.org/p/E1tlCOb32P

I ran into this by passing a `nil` `Publication` to cause a deliberate encoding error in my unit test, but to my surprise this did not trigger this short circuit.

Example of a caller that can pass in a `nil` pointer type - https://github.com/aporeto-inc/bahamut/blob/master/pubsub_nats.go#L69

---

If this patch is accepted, please create a new tag `v1.47.0` 🙏

### CODE REVIEW

**Comment by primalmotion** [comment]
Merging will increment the version automatically

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "elemental-fix-nil-check",
    "component": "elemental",
    "pr-id": "40",
    "commit-sha": "bf9977a12a64940ed1b3e5040c81da67b43009cf"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "elemental-fix-nil-check",
    "component": "elemental",
    "pr-id": "40",
    "commit-sha": "bf9977a12a64940ed1b3e5040c81da67b43009cf"
  }
]
```

**Comment by aaslamin** [comment]
Looks like this broke the 🌏

**Pull request merged**
